if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager", repos = c("http://cran.us.r-project.org"), dependencies = T, quiet = T, Ncpus = 1 );
BiocManager::install(version = "3.21", ask=F )
biocManager.status = require("BiocManager")
if( !biocManager.status ) stop("Cannot install BiocManager")
BiocManager::install("Biobase")
BiocManager::install("Biostrings")
BiocManager::install("biovizBase")
BiocManager::install("openxlsx")
BiocManager::install("regioneR")
BiocManager::install("reshape2")
BiocManager::install(c("stephenturner/annotables") )

install.packages("arules",repos= "http://cran.us.r-project.org")
install.packages("data.table",repos= "http://cran.us.r-project.org")
install.packages("ggrepel",repos= "http://cran.us.r-project.org")
install.packages("parallel",repos= "http://cran.us.r-project.org")
install.packages("sets",repos= "http://cran.us.r-project.org")
install.packages("splitstackshape",repos= "http://cran.us.r-project.org")
install.packages("writexl",repos= "http://cran.us.r-project.org")
install.packages(c('optparse','jsonlite'),repos='http://cran.r-project.org')
install.packages(c('git2r', 'httr', 'usethis', 'testthat','pkgdown'), repos = 'http://cran.rstudio.com/')
install.packages(c('doMC','foreach','doParallel'),repos= "http://cran.us.r-project.org")
devtools::install_github('mskilab/gUtils')
install.packages('vcfR',repos= "http://cran.us.r-project.org")
