name: 'Test-bioinformatics-transform-BAM'
description: 'This action tests the transformBAM.sh'

inputs:
    file_in: 'test-data/Sample_PM1_DNA75_1_P_1.md.bam'
    dir_out: test-data/output
    pm_in: 'PM1'
    pm_out: 'TEST1'

runs:
  using: 'docker'
  image: 'bioinfo-test'
  args:
    - 'static_value'
    - ${{ inputs.file_in }}
  entrypoint: '/entrypoint.sh'