# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
#  push:
#    branches: [ main ] 
  pull_request:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single jobs called "build" and "test"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: 'Build and test the image'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        # Runs a single command using the runners shell
      - name: Build the image
        id: build
        # run: docker build --rm -t bioinfo-test -f Dockerfile .
        run: docker pull eipm/bioinformatics:latest
           # Runs a set of commands using the runners shell
      - name: Test transformBAM
        # run:  docker run --rm --name bioinfo-test-github bioinfo-test bash -c "transformBAM.sh --file-in /test-data/Sample_PM1_DNA75_1_P_1_md.bam --dir-out /test-data/output --pm-in PM1 --pm-out TEST1"
        # uses: ./build_cache/bioinfo-test
        uses: docker://eipm/bioinformatics:latest
        id: bioinformatics-test
        with: 
            entrypoint: transformBAM.sh
            args: "--file-in /test-data/Sample_PM1_DNA75_1_P_1.md.bam  --dir-out /test-data/output --pm-in PM1 --pm-out TEST1"
              # --file-in: 'test-data/Sample_PM1_DNA75_1_P_1.md.bam'
              # --dir-out: test-data/output
              # --pm-in: 'PM1'
              # --pm-out: 'TEST1'
      - name: Collect docker logs
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Uploading artifact
        uses: actions/upload-artifact@v1
        with:
          name: bioinformatics logs
          path: ./logs/bioinformatics.log
        
